version: '3'

services:
  # Service pour l'application CyberTrust
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://cybertrust:cybertrust_password@db:5432/cybertrust
      - SESSION_SECRET=changez_cette_valeur_en_production
    depends_on:
      - db
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates

  # Service pour la base de données PostgreSQL
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=cybertrust
      - POSTGRES_PASSWORD=cybertrust_password
      - POSTGRES_DB=cybertrust
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service Nginx pour servir l'application (optionnel)
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - app

volumes:
  postgres_data: